let title = document.querySelector(".title");
let questionOne = document.querySelector(".question-1");
let questionTwoBasicMath = document.querySelector(".question-2-basic-math");
let questionTwoThrowChange = document.querySelector(".question-2-throw-change");
let questionThreeUrRight = document.querySelector(".question-3-ur-right");
let questionThreeFreebies = document.querySelector(".question-3-freebies");
let questionFourCustomers = document.querySelector(".question-4-customers");
let questionFiveDoordasher = document.querySelector(".question-5-Doordasher");
let customersRunEnd = document.querySelector(".customers-run-end");
let customersDuckEnd = document.querySelector(".customers-duck-end");
let doordasherHelpEnd = document.querySelector(".Doordasher-help-end");
let doordasherSoloEnd = document.querySelector(".Doordasher-solo-end");
let startButton = document.querySelector(".start-button");
let buttonOneQuestionOne = document.querySelector(".q1-option1");
let buttonTwoQuestionOne = document.querySelector(".q1-option2");
let buttonOneQuestionTwo = document.querySelector(".q2-option1");
let buttonTwoQuestionTwo = document.querySelector(".q2-option2");
let buttonOneQuestionThree = document.querySelector(".q3-option1");
let buttonTwoQuestionThree = document.querySelector(".q3-option2");
let buttonOneQuestionFour = document.querySelector(".q4-option1");
let buttonTwoQuestionFour = document.querySelector(".q4-option2");
let buttonOneQuestionFive = document.querySelector(".q5-option1");
let buttonTwoQuestionFive = document.querySelector(".q5-option2");
let restartButton = document.querySelector(".restart-button")

title.style.display = "block"
questionOne.style.display = "none";
questionTwoBasicMath.style.display = "none";
questionTwoThrowChange.style.display = "none";
questionThreeUrRight.style.display = "none";
questionThreeFreebies.style.display = "none";
questionFourCustomers.style.display = "none";
questionFiveDoordasher.style.display = "none";
customersRunEnd.style.display = "none";
customersDuckEnd.style.display = "none";
doordasherHelpEnd.style.display = "none";
doordasherSoloEnd.style.display = "none";
startButton.style.display = "inline-block";
buttonOneQuestionOne.style.display = "none";
buttonTwoQuestionOne.style.display = "none";
buttonOneQuestionTwo.style.display = "none";
buttonTwoQuestionTwo.style.display = "none";
buttonOneQuestionThree.style.display = "none";
buttonTwoQuestionThree.style.display = "none";
buttonOneQuestionFour.style.display = "none";
buttonTwoQuestionFour.style.display = "none";
buttonOneQuestionFive.style.display = "none"; 
buttonTwoQuestionFive.style.display = "none";
restartButton.style.display = "none";


startButton.addEventListener("click", function (){
    title.style.display = "none";
    questionOne.style.display = "block";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none";
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none";
    doordasherHelpEnd.style.display = "none";
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "inline-block";
    buttonTwoQuestionOne.style.display = "inline-block";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none";
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "none";
});

buttonOneQuestionOne.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "block";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none";
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none";
    doordasherHelpEnd.style.display = "none";
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "inline-block";
    buttonTwoQuestionTwo.style.display = "inline-block";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none";
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "none";
});

buttonTwoQuestionOne.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "block";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none";
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none";
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "inline-block";
    buttonTwoQuestionTwo.style.display = "inline-block";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "none";
});

buttonOneQuestionTwo.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "block";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none";
    customersRunEnd.style.display = "none"; 
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "inline-block";
    buttonTwoQuestionThree.style.display = "inline-block";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display= "none";
    restartButton.style.display = "none";
});

buttonTwoQuestionTwo.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "block";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none";
    customersRunEnd.style.display = "none"; 
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "inline-block";
    buttonTwoQuestionThree.style.display = "inline-block";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "none";
});

buttonOneQuestionThree.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "block";
    customersRunEnd.style.display = "none"; 
    customersDuckEnd.style.display = "none";
    doordasherHelpEnd.style.display = "none";
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "inline-block"; 
    buttonTwoQuestionFive.style.display = "inline-block";
    restartButton.style.display = "none";
});

buttonTwoQuestionThree.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "block";
    questionFiveDoordasher.style.display = "none"
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "inline-block"; 
    buttonTwoQuestionFour.style.display = "inline-block";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "none";
});

buttonOneQuestionFour.addEventListener("click", function (){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none"
    customersRunEnd.style.display = "block";
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "inline-block";
});

buttonTwoQuestionFour.addEventListener("click", function(){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none"
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "block"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "inline-block";
});

buttonOneQuestionFive.addEventListener("click", function (){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none"
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "block"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "inline-block";
});

buttonTwoQuestionFive.addEventListener("click", function (){
    title.style.display = "none";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none"
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "block";
    startButton.style.display = "none";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "inline-block";
});

restartButton.addEventListener("click", function(){
    title.style.display = "block";
    questionOne.style.display = "none";
    questionTwoBasicMath.style.display = "none";
    questionTwoThrowChange.style.display = "none";
    questionThreeUrRight.style.display = "none";
    questionThreeFreebies.style.display = "none";
    questionFourCustomers.style.display = "none";
    questionFiveDoordasher.style.display = "none"
    customersRunEnd.style.display = "none";
    customersDuckEnd.style.display = "none"; 
    doordasherHelpEnd.style.display = "none"; 
    doordasherSoloEnd.style.display = "none";
    startButton.style.display = "inline-block";
    buttonOneQuestionOne.style.display = "none";
    buttonTwoQuestionOne.style.display = "none";
    buttonOneQuestionTwo.style.display = "none";
    buttonTwoQuestionTwo.style.display = "none";
    buttonOneQuestionThree.style.display = "none";
    buttonTwoQuestionThree.style.display = "none";
    buttonOneQuestionFour.style.display = "none"; 
    buttonTwoQuestionFour.style.display = "none";
    buttonOneQuestionFive.style.display = "none"; 
    buttonTwoQuestionFive.style.display = "none";
    restartButton.style.display = "none";
})
